# Generated by Django 5.2.8 on 2025-11-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile'),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='resume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
