# Generated by Django 5.2.8 on 2025-11-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0002_studentdb_profile_studentdb_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdb',
            old_name='profile',
            new_name='img',
        ),
    ]
