# Generated by Django 5.2.8 on 2025-11-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0003_rename_profile_studentdb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
