# Generated by Django 5.2.8 on 2025-11-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0004_alter_studentdb_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('C_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('C_phone', models.IntegerField(blank=True, null=True)),
                ('C_Location', models.CharField(blank=True, max_length=50, null=True)),
                ('C_Description', models.TextField(blank=True, null=True)),
                ('C_Logo', models.ImageField(blank=True, null=True, upload_to='company_profile')),
                ('C_Password', models.CharField(blank=True, max_length=50, null=True)),
                ('C_ConfPassword', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
