# Generated by Django 5.2.8 on 2025-11-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0005_companydb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydb',
            old_name='C_Logo',
            new_name='logo',
        ),
    ]
