# Generated by Django 5.2.8 on 2025-11-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0006_rename_c_logo_companydb_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
