# Generated by Django 5.2.8 on 2025-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0007_alter_studentdb_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('stipend', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
