# Generated by Django 5.2.8 on 2025-11-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0008_internshippost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternshipPost',
            new_name='InternshipPostDB',
        ),
    ]
