# Generated by Django 5.2.8 on 2025-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0009_rename_internshippost_internshippostdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippostdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='internship_images/'),
        ),
    ]
