# Generated by Django 5.2.8 on 2025-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0010_internshippostdb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydb',
            name='C_Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
