# Generated by Django 5.2.8 on 2025-11-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0011_alter_companydb_c_email_alter_studentdb_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydb',
            old_name='C_ConfPassword',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='companydb',
            old_name='C_Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='companydb',
            old_name='C_Name',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='companydb',
            old_name='C_Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='studentdb',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='studentdb',
            old_name='c_password',
            new_name='is_verified',
        ),
    ]
