# Generated by Django 5.2.8 on 2025-11-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0012_rename_c_confpassword_companydb_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippostdb',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Company_Logo/'),
        ),
    ]
