# Generated by Django 5.2.8 on 2025-12-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_internship_internshipapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='location',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='image',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='position',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('internship', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='InternshipApplication',
        ),
    ]
