# Generated by Django 5.2.8 on 2025-12-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0013_internshippostdb_logo'),
        ('webapp', '0003_rename_location_internship_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.CreateModel(
            name='ApplicationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Applied', max_length=50)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Internship.internshippostdb')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Internship.studentdb')),
            ],
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
