# Generated by Django 5.2.8 on 2025-12-03 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0013_internshippostdb_logo'),
        ('webapp', '0004_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Internship.internshippostdb')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Internship.studentdb')),
            ],
        ),
    ]
