# Generated by Django 5.2.8 on 2025-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_savedinternship'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdb',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
