# Generated by Django 5.2.8 on 2025-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_applicationdb_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdb',
            name='company_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdb',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
