# Generated by Django 5.2.8 on 2025-12-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0013_internshippostdb_logo'),
        ('webapp', '0007_applicationdb_company_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Internship.companydb')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_Internship.studentdb')),
            ],
        ),
    ]
