# Generated by Django 5.2.8 on 2025-12-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0013_internshippostdb_logo'),
        ('webapp', '0008_companyreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationdb',
            unique_together={('student', 'internship')},
        ),
    ]
