# Generated by Django 5.2.8 on 2025-12-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_applicationdb_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationdb',
            unique_together=set(),
        ),
    ]
