# Generated by Django 5.2.8 on 2026-01-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Internship', '0013_internshippostdb_logo'),
        ('webapp', '0011_studentnotification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyreview',
            unique_together={('student', 'company')},
        ),
    ]
